package com.harshal.exception;

import java.util.Scanner;

public class Exception_demo {

	public static void main(String[] args) {

		int marks[] = { 10, 20, 30, 40, 50, 60 };
//		int marks[] = new int[6];
//		marks[0] = 10;
//		marks[1] = 20;
//		marks[2] = 30;
//		marks[3] = 40;
//		marks[4] = 50;
//		marks[5] = 60;

		// Try --> Allows to define a block of code to be tested for errors while it is being executed
		// Catch --> Catches exceptions generated by try statements
		// Finally --> No matter exception occurred or not finally block of code execute explicitly.
		
		try {        

			Scanner sc = new Scanner(System.in);

			System.out.println("Enter the integer array position : ");
			int position = sc.nextInt();
			int size = marks[position];

			System.out.println("Enter the number you want to divide : ");
			double num = sc.nextDouble();

			double res = size / num;
			System.out.println("Division : " + res);              

		} 
		catch (Exception e) {     
			System.out.println("Exception occured : " + e );
		} 
		finally {             
			System.out.println("****Thank You****");
		}
	}
}
